volumes:
  dockerdev-mysql-volume:
    external: true
  dockerdev-workspace-volume:
    external: true

services:
  db:
    container_name: dockerdev-db
    image: percona
    volumes:
      - ./conf.d/mysql/my.cnf:/etc/my.cnf.d/development.cnf:ro
      - dockerdev-mysql-volume:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD
    ports:
      - 127.0.0.1:3306:3306

  mailcatch:
    image: mailhog/mailhog

  php82:
    build:
      context: build/dist/php
      args:
        - FROM_TAG=php82-fpm
    environment:
      - "BLACKFIRE_AGENT_SOCKET=unix:///dev/null"
    volumes:
      - dockerdev-workspace-volume:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
  php83:
    build:
      context: build/dist/php
      args:
        - FROM_TAG=php83-fpm
    environment:
      - "BLACKFIRE_AGENT_SOCKET=unix:///dev/null"
    volumes:
      - dockerdev-workspace-volume:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  web:
    build:
      context: build/dist/web
    volumes:
        - dockerdev-workspace-volume:/data:ro
    environment:
      - DOMAINSUFFIX
  ssl:
    depends_on:
      - web
    build:
      context: build/dist/ssl
    ports:
        - "80:80"
        - "443:443"
